package GUI;

//Importar Clases: import DAL.Cliente; 
import DAL.Cliente;
import com.sun.glass.events.KeyEvent; 
import com.toedter.calendar.JDateChooser; 
import java.awt.Image; 
import java.awt.event.ItemEvent; 
import java.awt.event.KeyAdapter; 
import java.io.File; 
import java.io.FileInputStream; 
import java.io.FileWriter; 
import java.nio.file.Files; 
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING; 
import java.text.SimpleDateFormat; 
import java.util.Calendar; 
import java.util.regex.Matcher; 
import java.util.regex.Pattern; 
import javax.swing.Icon; 
import javax.swing.ImageIcon; 
import javax.swing.JFileChooser; 
import javax.swing.JFrame; 
import javax.swing.JOptionPane; 
import javax.swing.JTable; 
import javax.swing.JTextField; 
import javax.swing.RowFilter; 
import javax.swing.filechooser.FileNameExtensionFilter; 
import javax.swing.table.DefaultTableModel; 
import javax.swing.table.TableRowSorter; 


public class JFrm_MantenimientoCliente extends javax.swing.JFrame {

       //Declarar una Variable de Tipo: JFrame 
    JFrame Formulario; 

    //Declarar variable de tipo: DefaultTableModel (Modelo de Tabla) 
    DefaultTableModel Modelo; 
     
    //Declarar variable de tipo: TableRowSorter (Clasificador de Filas de Tabla) 
    TableRowSorter TFiltroFila; //Variable para Filtrar Datos en un Cojunto de Filas de una Tabla 
     
    //Declarar variable de tipo: Entero     
    int Codigo=1, Filas; 
     
     //Establecer el Directorio del Proyecto, de donde se desea leer y guardar datos del Archivo de Texto 
    String DirectorioNacionalidad = new 
File("src/Archivo_Datos/Registro_Nacionalidad.txt").getAbsolutePath(); 
    String DirectorioDocIdentidad = new 
File("src/Archivo_Datos/Registro_Documentos_Identidad.txt").getAbsolutePath(); 
    String DirectorioDepartamento = new 
File("src/Archivo_Datos/Registro_Departamentos.txt").getAbsolutePath(); 
    String DirectorioProvincia = new 
File("src/Archivo_Datos/Registro_Provincias.txt").getAbsolutePath(); 
    String DirectorioDistrito = new 
File("src/Archivo_Datos/Registro_Distritos.txt").getAbsolutePath(); 
    String DirectorioCliente = new 
File("src/Archivo_Datos/Registro_Clientes.txt").getAbsolutePath(); 
    //Instanciar la Clase: Persona, a través de un Objeto 
    Cliente ObjCliente = new Cliente ("","","","","","","","","","","","","","","",""); 
     
    //Declarar una variable Local de tipo: String 
    String CodCliente; 
          
    //Declarar un variable de tipo: SimpleDateFormat (Formato de Fecha Simple)     SimpleDateFormat FormatoFecha = new SimpleDateFormat("dd/MM/yyyy");  
     

    
    public JFrm_MantenimientoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_MantenimientoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_MantenimientoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_MantenimientoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_MantenimientoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_MantenimientoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
